DROP DATABASE IF EXISTS teste;
CREATE DATABASE teste;
\c teste
CREATE TABLE login(username VARCHAR(32) NOT NULL, password VARCHAR(32) NOT NULL);
DROP USER IF EXISTS dba;
CREATE USER dba WITH PASSWORD 'dba123';
GRANT ALL PRIVILEGES ON DATABASE teste TO dba;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON tables TO dba;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, USAGE ON sequences TO dba;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO dba;
INSERT INTO login VALUES('alice', 'alice123');
